Add `environment` command
twilio-infra-as-code/plugin-twilio-infra pull request #17
Opened 2021-04-20 17:32 UTC by vernig

Add `infra:environment` commands: 

* `infra:environment:set`: set the environment (i.e. Pulumi stack)
* `infra:environment:new`: create a new environment (i.e. Pulumi stack) for the projected selected in the Twilio CLI
* `infra:environment:get`: get the current environment (i.e. Pulumi stack)

2021-04-20 17:32 UTC, vernig commented
Tested with: 

* Deploy
  * Run `twilio infra:deploy` 
  * Check that `.twilio-infra` is added 
* Attempt to deploy to the wrong environment
  * After deployment change twilio CLI profile to a different project. 
  * Run `twilio infra:deploy`
  * Should get an error saying that the environment is already associated to a different account
* Destroy 
  * Run `twilio infra:destroy`
  * Check that `.twilio-infra` is removed
* Set a non existing environemnt
  * Run `twilio infra:environment:set fsdhjkhsdkjadh`
  * Should return `Environment fsdhjkhsdkjadh is not defined`
* Add a new environment to an existing deployment
  * Make sure the project selected in the CLI has an entry in `.twilio-infra`
  * Run `twilio infra:environment:set fsdhjkhsdkjadh`
  * Should get n error `Your Twilio project `ACxxxx` is already associated to another environment (xxx)`
* Add a new environment
  * Login to a new project in the CLI 
  * Run `twilio infra:environment:new prod`
  * Should succesfully create a new environment. Check that the eenvironment is added to `.twilio-infra` with `deployed = false`

2021-04-20 17:32 UTC, vernig commented
@bermudezmt @kaiquelupo I started implementing the environments. The only test I performed so far are the one in the previous comment. Please feel free to add new comment(s) with other test cases you would like to implement.

2021-05-05 03:44 UTC, bermudezmt requested changes
Added some commit suggestions. 

Spellcheck, @vernig 😜

2021-05-05 03:44 UTC, bermudezmt commented on src/commands/infra/environment/new.js
> +          'New environment created. When you are ready, use\n\n  $ twilio infra:deploy\n\nto deploy it to your Twilio prpject'
```suggestion
          'New environment created. When you are ready, use\n\n  $ twilio infra:deploy\n\nto deploy it to your Twilio project'
```

2021-05-05 03:44 UTC, bermudezmt commented on src/commands/infra/destroy.js
> +      Printer.printSuccess('Resource(s) destroyed succesfully!');
```suggestion
      Printer.printSuccess('Resource(s) destroyed successfully!');
```

2021-05-05 03:44 UTC, bermudezmt commented on src/commands/infra/deploy.js
> +        `The current stack is already deployed to ${deployment}. Please switch to that profile or define a new envirnoment`
```suggestion
        `The current stack is already deployed to ${deployment}. Please switch to that profile or define a new environment`
```

2021-05-11 20:16 UTC, vernig commented on src/commands/infra/destroy.js
> +      Printer.printSuccess('Resource(s) destroyed succesfully!');
Thanks @bermudezmt !

2021-05-11 20:16 UTC, vernig commented on src/commands/infra/deploy.js
> +        `The current stack is already deployed to ${deployment}. Please switch to that profile or define a new envirnoment`
Thanks @bermudezmt !

2021-05-11 21:22 UTC, vernig commented
@kaiquelupo @bermudezmt the last commit bd36e4b adds the check before creating a new environment. You can test this using the following step: 

* Add a new environment to a non deployed project
  * Create a new IaC project or use an existing one that has not been deployed
  * Run twilio infra:environment:new <new_environment_name> 
  * CLI should warn you that you are overwriting the environment associated to the project and prompt to continue

```
The current Twilio project (ACxxxxx) is already associated to environment "xxxx", but it's not deployed. 
Are you sure you want to associate a new environment to it? Y/n
````
I updated the [comment above](https://github.com/twilio-infra-as-code/plugin-twilio-infra/pull/17#issuecomment-823469048) with the new test.

2021-05-19 03:59 UTC, bermudezmt commented
Works beautifully, thank you!

2021-05-19 03:59 UTC, merged