Feature: added option to use the --yes flag in deploy and destroy
twilio-infra-as-code/plugin-twilio-infra pull request #31
Opened 2021-08-12 12:40 UTC by TheGarkine

This should allow use of the plugin in CICD pipelines again. I added an option --yes, such that normal operation does not result in accidental creation/destruction of stacks.

2021-08-16 17:10 UTC, vernig commented
Thanks @TheGarkine for the proposed implementation. As a matter of fact we already have a `non-interactive` mode for the pulumi command, and I'd rather use that instead of passing the `--yes` flag. 

So my thinking is to use a more descriptive `--non-interactive` / `-n` flag which attempts to execute commands for the underlying IaC provider in non interactive mode. 

I tested using: 
```
runPulumiCommand(command, false, this.twilioClient); 
```
and the resources are created correctly without any prompt to the user. The only thing is that I don't see any printout but that may be a bug in the implementation of the non interactive `else` branch (I need more investigations). 

Still, I really like your idea of passing down pulumi's flag into the CLI, so we should probably work on that separately in another PR. 

Back to this PR, can I ask you to make the following changes: 

* Fix the linter errors (I'm about to reinforce linting in this project): 
```
/plugin-twilio-infra/src/commands/infra/deploy.js
   3:27   error  Strings must use singlequote  quotes
  24:20   error  Strings must use singlequote  quotes
  40:106  error  Missing trailing comma        comma-dangle
  41:7    error  Missing trailing comma        comma-dangle

/plugin-twilio-infra/src/commands/infra/destroy.js
   3:27   error  Strings must use singlequote  quotes
  13:20   error  Strings must use singlequote  quotes
  29:107  error  Missing trailing comma        comma-dangle
  30:7    error  Missing trailing comma        comma-dangle
```
* Change `--yes` to `--non-interactive` / `-n`
* Change the call to `runPulumiCommand()` to: 
```
runPulumiCommand(command, !this.flags.nonInteractive, this.twilioClient);
```

Let me know what you think, and thanks for your contributions!!

2021-08-16 17:10 UTC, vernig requested changes

2021-08-16 17:10 UTC, vernig commented on src/commands/infra/deploy.js
> +      description: 'Passes through the --yes option to pulumi. Deploys without interactive confirmation.'
Could you change the description to only:
```
Deploys without interactive confirmation
```

2021-08-16 17:10 UTC, vernig commented on src/commands/infra/destroy.js
> +      description: 'Passes through the --yes option to pulumi. Destroys without interactive confirmation.'
Same for this one: 
```
Destroys without interactive confirmation.
```

2021-08-17 07:27 UTC, TheGarkine commented
Hey @vernig,

Thats a valid point. Honestly, I was not experimenting with the non-interactive mode, and just looked for a quick solution without touching too much existent code!

I will resolve this today and will let you know!

2021-08-17 08:14 UTC, TheGarkine commented
@vernig, Well I at least know why no output is given when using non-interactive mode; the stdio is not given, therefore the stdout is read to a variable which is not used. Also, omitting the --yes flag results in an error on my machine (Win10; pulumi 3.5.1). I would suggest using interactive mode for now, and maybe renaming the mode (but I didn't come up with a better naming scheme yet.  Maybe we should give the option to overwrite the default stdio option?

2021-08-17 08:15 UTC, vernig commented
Hey @TheGarkine, sure no problem, and thanks again for helping with this. As soon as this is merged I'll work on a proper solution to implement passing down argument to Pulumi CLI

2021-08-17 08:17 UTC, vernig commented
> the stdio is not given, therefore the stdout is read to a variable which is not used.

Thanks! We definitely need to fix it. 

>  Also, omitting the --yes flag results in an error on my machine (Win10; pulumi 3.5.1). 

That's interesting. Can you share which error you are getting? I don't have a quick way of testing on Windows at the moment

2021-08-17 08:21 UTC, TheGarkine commented
Need to reproduce later, but the error was something like "Cannot deploy in non-interactive mode without the --yes flag". I checked the pulumi source code the other day, and they realize when their command is not in an interactive environment (or in CICD) and then require this flag, so I don't think we can get around that.

2021-08-17 08:23 UTC, vernig commented
> Need to reproduce later, but the error was something like "Cannot deploy in non-interactive mode without the --yes flag". 

Thanks @TheGarkine. It's weird because on macOS works fine. Let me find a windows machine to test it. If I reproduce it, I'll speak to the Pulumi folks about it

2021-08-17 08:25 UTC, TheGarkine commented
https://github.com/pulumi/pulumi/blob/a952140b34c667d005116ee53be08077b5863948/sdk/go/common/util/cmdutil/console.go#L48

2021-08-18 12:39 UTC, vernig commented
LGTM for now @TheGarkine. Thank you so much for your contribution. I'm going to raise an issue to track the following features we discussed here: 

* Pass Pulumi flags down from the Twilio CLI 
* Implement non interactive mode using:
 ```
runPulumiCommand(command, false, this.twilioClient);
```

2021-08-18 12:41 UTC, merged

2021-08-18 12:42 UTC, vernig commented
:tada: This PR is included in version 0.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/plugin-twilio-infra/v/0.4.0)
- [GitHub release](https://github.com/twilio-infra-as-code/plugin-twilio-infra/releases/tag/v0.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: